import type { TemplateDefinition } from '../types'
import { makeSample, samplePhotos } from '../sample'

const FONT_BODY = "'Hanken Grotesk', sans-serif"

/**
 * Variações adicionais por categoria. O objetivo é que cada categoria tenha uma
 * "coleção" de modelos com identidades distintas: além do tema (cores/tipografia),
 * cada variação usa um LAYOUT diferente do modelo já existente na mesma categoria,
 * entregando uma experiência de navegação própria.
 *
 * Adicionar um novo modelo = acrescentar um objeto aqui. Ele aparece
 * automaticamente na galeria, no fluxo de criação e no catálogo mock via registry.
 */
export const collectionTemplates: TemplateDefinition[] = [
  // ❤️ Declaração de Amor — carta minimalista (o outro é cinematográfico)
  {
    slug: 'amor-carta',
    layout: 'letter',
    name: 'Declaração em Carta',
    category: 'amor',
    tributeTypeSlug: 'namorados',
    description: 'Uma carta elegante e centrada, para dizer tudo com poucas palavras.',
    theme: {
      primaryColor: '#be123c',
      accentColor: '#fb7185',
      fontDisplay: "'Cormorant Garamond', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #fff7f9 0%, #fdeef2 100%)',
      mode: 'light',
    },
    animation: { speed: 'slow', entrance: 'fade' },
    effects: [],
    capabilities: { maxPhotos: 6, supportsVideo: false, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'card' } },
      { id: 'letter', type: 'typewriter' },
      { id: 'gallery', type: 'gallery', config: { layout: 'grid', title: 'Nós' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com amor,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Meu amor',
      senderName: 'Eu',
      title: 'Para você',
      subtitle: 'Uma carta que eu precisava escrever',
      message:
        'Escrevo para dizer o óbvio que nunca é demais: eu te amo.\nAmo o jeito que você transforma os dias comuns em algo que vale a pena lembrar.',
      closingMessage: 'Seu, hoje e sempre.',
      signature: 'Com amor, eu',
      photos: samplePhotos(3, 'Nós'),
    }),
  },

  // ❤️ Pedido de Namoro — carta animada (o outro é pedido interativo)
  {
    slug: 'pedido-namoro-carta',
    layout: 'envelope',
    name: 'Convite em Carta',
    category: 'pedido-namoro',
    tributeTypeSlug: 'pedido',
    description: 'Um envelope que abre e revela o convite, linha a linha.',
    theme: {
      primaryColor: '#db2777',
      accentColor: '#f9a8d4',
      fontDisplay: "'Dancing Script', cursive",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #fdf2f8 0%, #fce7f3 100%)',
      mode: 'light',
    },
    animation: { speed: 'slow', entrance: 'fade' },
    effects: ['hearts'],
    capabilities: { maxPhotos: 6, supportsVideo: false, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'card', eyebrow: 'Tenho um convite' } },
      { id: 'letter', type: 'typewriter' },
      { id: 'gallery', type: 'gallery', config: { layout: 'grid', title: 'A gente' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Esperando por você,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Você',
      senderName: 'Eu',
      title: 'Uma carta especial',
      subtitle: 'Abra com carinho',
      message:
        'Passei dias pensando em como te dizer isso.\nEntão resolvi escrever: eu quero namorar com você.',
      closingMessage: 'Quer namorar comigo?',
      signature: 'No aguardo, eu',
      photos: samplePhotos(3, 'A gente'),
      question: 'Quer namorar comigo?',
      celebration: 'Ela disse SIM! 💞',
    }),
  },

  // 💍 Pedido de Casamento — cinematográfico (o outro é pedido interativo)
  {
    slug: 'pedido-casamento-cinema',
    layout: 'cinematic',
    name: 'Pedido Cinematográfico',
    category: 'pedido-casamento',
    tributeTypeSlug: 'pedido',
    description: 'Fotos em tela cheia com clima de trailer até a grande pergunta.',
    theme: {
      primaryColor: '#9f1239',
      accentColor: '#fb7185',
      fontDisplay: "'Playfair Display', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #0b0608 0%, #1c0e14 100%)',
      mode: 'dark',
    },
    animation: { speed: 'slow', entrance: 'fade' },
    effects: ['hearts', 'fireworks'],
    capabilities: { maxPhotos: 16, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', parallax: true } },
      { id: 'slider', type: 'photoSlider', config: { title: 'Nossa história' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Tudo o que sinto' } },
      { id: 'final', type: 'finalMessage', config: { text: 'Casa comigo?' } },
      { id: 'signature', type: 'signature', config: { prefix: 'Para sempre,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Meu amor',
      senderName: 'Eu',
      title: 'A nossa história',
      subtitle: 'Cada cena nos trouxe até aqui',
      message: 'Se a vida é um filme, quero você em todas as cenas que ainda vou viver.',
      closingMessage: 'Casa comigo?',
      signature: 'Para sempre, eu',
      photos: samplePhotos(6, 'Nós'),
      messages: ['Você é o meu final feliz.', 'Quero recomeçar com você todos os dias.'],
    }),
  },

  // 👰 Casamento — álbum folheável (o outro é storytelling)
  {
    slug: 'casamento-album',
    layout: 'album',
    name: 'Álbum dos Noivos',
    category: 'casamento',
    tributeTypeSlug: 'casamento',
    description: 'Um álbum que se folheia, com uma memória em cada página.',
    theme: {
      primaryColor: '#a16207',
      accentColor: '#ddb892',
      fontDisplay: "'Cormorant Garamond', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #fbf7f0 0%, #f3ead9 100%)',
      mode: 'light',
    },
    animation: { speed: 'normal', entrance: 'slide-up' },
    effects: ['petals'],
    capabilities: { maxPhotos: 24, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'card' } },
      { id: 'gallery', type: 'gallery', config: { layout: 'masonry', title: 'Nosso álbum' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Votos e desejos' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com amor,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Nós dois',
      senderName: 'Os noivos',
      title: 'O nosso grande dia',
      subtitle: 'Cada página, uma lembrança',
      message: 'Reunimos aqui os momentos que nos trouxeram até o altar.',
      closingMessage: 'E que a nossa história continue para sempre.',
      signature: 'Com amor, os noivos',
      photos: samplePhotos(6, 'Nós'),
      messages: ['Que a vida a dois seja leve.', 'Um amor para todas as estações.'],
    }),
  },

  // 🎂 Aniversário — rolagem clássica (o outro é cinematográfico)
  {
    slug: 'aniversario-scroll',
    layout: 'scroll',
    name: 'Aniversário Clássico',
    category: 'aniversario',
    tributeTypeSlug: 'aniversario',
    description: 'Rolagem festiva com contagem regressiva, galeria e recados.',
    theme: {
      primaryColor: '#f97316',
      accentColor: '#f43f5e',
      fontDisplay: "'Poppins', sans-serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #fff7ed 0%, #fef2f2 100%)',
      mode: 'light',
    },
    animation: { speed: 'fast', entrance: 'zoom' },
    effects: ['confetti'],
    capabilities: { maxPhotos: 24, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'card', eyebrow: 'É dia de festa!' } },
      { id: 'countdown', type: 'countdown', config: { mode: 'countdown', title: 'Contagem para a festa' } },
      { id: 'gallery', type: 'gallery', config: { layout: 'masonry', title: 'Retrospectiva' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Recados' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com carinho,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Maria',
      senderName: 'Seus amigos',
      title: 'Feliz Aniversário!',
      subtitle: 'Um dia para celebrar você',
      message: 'Que este novo ciclo venha cheio de alegrias e boas surpresas.',
      closingMessage: 'Muitos anos de vida!',
      signature: 'Com carinho, todos nós',
      specialDate: new Date(Date.now() + 86_400_000 * 12).toISOString(),
      photos: samplePhotos(6, 'Festa'),
      messages: ['Parabéns! — Bianca', 'Tudo de bom pra você! — Rafa'],
    }),
  },

  // 💐 Dia das Mães — carta (o outro é álbum)
  {
    slug: 'dia-das-maes-carta',
    layout: 'letter',
    name: 'Carta para Mãe',
    category: 'dia-das-maes',
    tributeTypeSlug: 'dia-das-maes',
    description: 'Uma carta delicada, feita para emocionar em poucas linhas.',
    theme: {
      primaryColor: '#db2777',
      accentColor: '#f9a8d4',
      fontDisplay: "'Cormorant Garamond', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #fff5f9 0%, #fdeef4 100%)',
      mode: 'light',
    },
    animation: { speed: 'slow', entrance: 'fade' },
    effects: [],
    capabilities: { maxPhotos: 6, supportsVideo: false, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'card', eyebrow: 'Para você, mãe' } },
      { id: 'letter', type: 'typewriter' },
      { id: 'gallery', type: 'gallery', config: { layout: 'grid', title: 'Nós duas' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com amor,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Mãe',
      senderName: 'Seu filho(a)',
      title: 'Para a minha mãe',
      subtitle: 'Palavras que vêm do coração',
      message:
        'Mãe, obrigada por ser meu primeiro abraço e meu porto seguro.\nCada coisa boa em mim começou em você.',
      closingMessage: 'Te amo mais do que consigo dizer.',
      signature: 'Com amor, seu filho(a)',
      photos: samplePhotos(3, 'Nós'),
    }),
  },

  // 👨 Dia dos Pais — cinematográfico (o outro é timeline)
  {
    slug: 'dia-dos-pais-cinema',
    layout: 'cinematic',
    name: 'Homenagem ao Pai',
    category: 'dia-dos-pais',
    tributeTypeSlug: 'dia-dos-pais',
    description: 'Fotos em tela cheia com clima de documentário afetivo.',
    theme: {
      primaryColor: '#0f766e',
      accentColor: '#5eead4',
      fontDisplay: "'Poppins', sans-serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #07110f 0%, #0f1f1c 100%)',
      mode: 'dark',
    },
    animation: { speed: 'normal', entrance: 'fade' },
    effects: [],
    capabilities: { maxPhotos: 20, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', parallax: true } },
      { id: 'slider', type: 'photoSlider', config: { title: 'Grandes momentos' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'O que aprendi com você' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com admiração,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Pai',
      senderName: 'Seu filho(a)',
      title: 'Ao meu herói',
      subtitle: 'Obrigado por tudo, pai',
      message: 'Você me ensinou que força de verdade mora na gentileza e na presença.',
      closingMessage: 'Meu maior exemplo, sempre.',
      signature: 'Com admiração, seu filho(a)',
      photos: samplePhotos(6, 'Pai e eu'),
      messages: ['Obrigado por cada conselho.', 'Meu porto seguro de sempre.'],
    }),
  },

  // 👶 Chá de Bebê — rolagem festiva (o outro é álbum)
  {
    slug: 'cha-de-bebe-scroll',
    layout: 'scroll',
    name: 'Chá de Bebê Festivo',
    category: 'cha-de-bebe',
    tributeTypeSlug: 'cha-de-bebe',
    description: 'Anúncio fofo com contagem para a chegada e recadinhos.',
    theme: {
      primaryColor: '#38bdf8',
      accentColor: '#f9a8d4',
      fontDisplay: "'Fredoka', sans-serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #f0f9ff 0%, #fdf2f8 100%)',
      mode: 'light',
    },
    animation: { speed: 'normal', entrance: 'slide-up' },
    effects: ['stars'],
    capabilities: { maxPhotos: 16, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'card', eyebrow: 'Estamos esperando por você' } },
      { id: 'countdown', type: 'countdown', config: { mode: 'countdown', title: 'Contagem para a chegada' } },
      { id: 'gallery', type: 'gallery', config: { layout: 'grid', title: 'Primeiros momentos' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Desejos para o bebê' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com amor,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Nosso bebê',
      senderName: 'Papai e mamãe',
      title: 'Bem-vindo, pequeno amor',
      subtitle: 'Já te amamos tanto!',
      message: 'A nossa casa e o nosso coração já estão prontos para te receber.',
      closingMessage: 'Mal podemos esperar para te conhecer.',
      signature: 'Com amor, papai e mamãe',
      specialDate: new Date(Date.now() + 86_400_000 * 40).toISOString(),
      photos: samplePhotos(5, 'À espera'),
      messages: ['Que venha com muita saúde!', 'Já é o mais amado do mundo.'],
    }),
  },

  // 🎓 Formatura — cinematográfico (o outro é timeline)
  {
    slug: 'formatura-cinema',
    layout: 'cinematic',
    name: 'Formatura Cinematográfica',
    category: 'formatura',
    tributeTypeSlug: 'formatura',
    description: 'A conquista em tela cheia, como o trailer de um novo começo.',
    theme: {
      primaryColor: '#1d4ed8',
      accentColor: '#fbbf24',
      fontDisplay: "'Poppins', sans-serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #070b16 0%, #101a2e 100%)',
      mode: 'dark',
    },
    animation: { speed: 'normal', entrance: 'zoom' },
    effects: ['confetti'],
    capabilities: { maxPhotos: 24, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', eyebrow: 'Conseguimos!' } },
      { id: 'slider', type: 'photoSlider', config: { title: 'A trajetória' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Recados de quem torceu' } },
      { id: 'final', type: 'finalMessage', config: { text: 'Que venham os próximos capítulos!' } },
      { id: 'signature', type: 'signature', config: { prefix: 'Com orgulho,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Formando(a)',
      senderName: 'Sua família',
      title: 'Parabéns, formando!',
      subtitle: 'Este é só o começo',
      message: 'Anos de esforço se transformaram nesta grande conquista. Orgulho define.',
      closingMessage: 'O futuro é seu.',
      signature: 'Com orgulho, sua família',
      photos: samplePhotos(6, 'Trajetória'),
      messages: ['Você merece cada aplauso!', 'Que venham grandes voos.'],
    }),
  },

  // 🎄 Natal — rolagem aconchegante (o outro é storytelling)
  {
    slug: 'natal-scroll',
    layout: 'scroll',
    name: 'Natal Aconchegante',
    category: 'natal',
    tributeTypeSlug: 'natal',
    description: 'Uma mensagem calorosa de Natal, com galeria e votos.',
    theme: {
      primaryColor: '#b91c1c',
      accentColor: '#e5c07b',
      fontDisplay: "'Fraunces', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #0d2818 0%, #14110f 100%)',
      mode: 'dark',
    },
    animation: { speed: 'slow', entrance: 'fade' },
    effects: ['snow'],
    capabilities: { maxPhotos: 16, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', eyebrow: 'Feliz Natal' } },
      { id: 'message', type: 'typewriter' },
      { id: 'gallery', type: 'gallery', config: { layout: 'masonry', title: 'Momentos em família' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Votos de Natal' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com carinho,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Você e sua família',
      senderName: 'Com carinho',
      title: 'Feliz Natal',
      subtitle: 'Que seu Natal seja repleto de luz',
      message: 'Que esta época aqueça o coração e reúna quem a gente ama.',
      closingMessage: 'Um Natal cheio de amor para você.',
      signature: 'Com carinho, sua família',
      photos: samplePhotos(5, 'Natal'),
      messages: ['Que 2026 seja abençoado!', 'Paz e alegria para os seus.'],
    }),
  },

  // 🎆 Ano Novo — rolagem retrospectiva (o outro é cinematográfico)
  {
    slug: 'ano-novo-scroll',
    layout: 'scroll',
    name: 'Retrospectiva do Ano',
    category: 'ano-novo',
    tributeTypeSlug: 'ano-novo',
    description: 'Uma retrospectiva com linha do tempo e votos para o novo ano.',
    theme: {
      primaryColor: '#eab308',
      accentColor: '#fde68a',
      fontDisplay: "'Space Grotesk', sans-serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #0b1020 0%, #131a33 100%)',
      mode: 'dark',
    },
    animation: { speed: 'normal', entrance: 'slide-up' },
    effects: ['fireworks'],
    capabilities: { maxPhotos: 20, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', eyebrow: 'Um brinde ao novo ano' } },
      { id: 'timeline', type: 'timeline', config: { title: 'O que vivemos este ano' } },
      { id: 'gallery', type: 'gallery', config: { layout: 'masonry', title: 'Melhores momentos' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Votos para o novo ano' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com esperança,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Você',
      senderName: 'Com carinho',
      title: 'Um brinde ao novo ano',
      subtitle: 'Que venha um ano de conquistas',
      message: 'Olhar para trás com gratidão e para frente com esperança.',
      closingMessage: 'Que o próximo ano seja o melhor de todos.',
      signature: 'Com esperança, sempre',
      photos: samplePhotos(5, 'Momentos'),
      messages: ['Novos sonhos pela frente!', 'Que venham boas surpresas.'],
    }),
  },

  // 🕊️ Memorial — carta serena (o outro é álbum)
  {
    slug: 'memorial-carta',
    layout: 'letter',
    name: 'Memorial em Carta',
    category: 'memorial',
    tributeTypeSlug: 'memorial',
    description: 'Uma despedida serena e minimalista, focada nas palavras.',
    theme: {
      primaryColor: '#a8763e',
      accentColor: '#e7d3a6',
      fontDisplay: "'Cormorant Garamond', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #faf7f1 0%, #f1e9db 100%)',
      mode: 'light',
    },
    animation: { speed: 'slow', entrance: 'fade' },
    effects: [],
    capabilities: { maxPhotos: 6, supportsVideo: false, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'card', eyebrow: 'Em memória' } },
      { id: 'letter', type: 'typewriter' },
      { id: 'gallery', type: 'gallery', config: { layout: 'grid', title: 'Recordações' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com saudade,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'José',
      senderName: 'A família',
      title: 'Em memória de José',
      subtitle: '1948 — 2024',
      message:
        'Guardamos você em cada gesto de carinho que aprendemos.\nSua presença segue viva nas histórias que contamos.',
      closingMessage: 'Para sempre em nossos corações.',
      signature: 'Com saudade, sua família',
      photos: samplePhotos(3, 'Recordação'),
    }),
  },

  // 🎉 Datas Comemorativas — rolagem versátil (o outro é álbum)
  {
    slug: 'datas-scroll',
    layout: 'scroll',
    name: 'Data Comemorativa',
    category: 'datas',
    tributeTypeSlug: 'dia-da-mulher',
    description: 'Um modelo versátil para qualquer data especial do calendário.',
    theme: {
      primaryColor: '#9333ea',
      accentColor: '#e879f9',
      fontDisplay: "'Poppins', sans-serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #faf5ff 0%, #fdf2f8 100%)',
      mode: 'light',
    },
    animation: { speed: 'normal', entrance: 'slide-up' },
    effects: ['petals'],
    capabilities: { maxPhotos: 16, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'card' } },
      { id: 'message', type: 'typewriter' },
      { id: 'gallery', type: 'gallery', config: { layout: 'masonry', title: 'Momentos' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Mensagens' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com carinho,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Você',
      senderName: 'Com carinho',
      title: 'Uma data para celebrar',
      subtitle: 'Porque momentos especiais merecem ser lembrados',
      message: 'Toda data especial fica ainda melhor quando é compartilhada com quem amamos.',
      closingMessage: 'Que esta data seja inesquecível.',
      signature: 'Com carinho',
      photos: samplePhotos(5, 'Momentos'),
      messages: ['Um dia para guardar na memória.', 'Que se repita por muitos anos.'],
    }),
  },
]
