import type { TemplateDefinition } from '../types'
import { makeSample, samplePhotos } from '../sample'

const inDays = (days: number) => new Date(Date.now() + 86_400_000 * days).toISOString()

const FONT_BODY = "'Hanken Grotesk', sans-serif"

/**
 * Conjunto de templates de ocasiões da biblioteca. Adicionar um novo modelo =
 * acrescentar um objeto aqui (ou criar um arquivo dedicado) e ele aparece
 * automaticamente na galeria e no catálogo mock via registry.
 */
export const occasionTemplates: TemplateDefinition[] = [
  {
    slug: 'dia-das-maes',
    layout: 'album',
    name: 'Dia das Mães',
    category: 'dia-das-maes',
    tributeTypeSlug: 'dia-das-maes',
    description: 'Homenagem delicada com pétalas, álbum de memórias e mensagem final assinada.',
    theme: {
      primaryColor: '#ec4899',
      accentColor: '#f9a8d4',
      fontDisplay: "'Playfair Display', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #fff5f9 0%, #fdeef4 100%)',
      mode: 'light',
    },
    animation: { speed: 'normal', entrance: 'slide-up' },
    effects: ['petals'],
    capabilities: { maxPhotos: 20, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'card', eyebrow: 'Para você, mãe' } },
      { id: 'msg', type: 'typewriter' },
      { id: 'gallery', type: 'gallery', config: { layout: 'masonry', title: 'Álbum de memórias' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Do fundo do coração' } },
      { id: 'video', type: 'video' },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com amor,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Mãe',
      senderName: 'Seus filhos',
      title: 'Para a melhor mãe do mundo',
      subtitle: 'Obrigado por todo amor e cuidado de sempre',
      message: 'Seu colo foi meu primeiro lar e seu amor, meu maior porto seguro.',
      closingMessage: 'Te amamos mais do que as palavras podem dizer.',
      signature: 'Seus filhos',
      photos: samplePhotos(6, 'Memória'),
      messages: [
        'Obrigada por cada abraço nos dias difíceis.',
        'Você é a força mais gentil que conheço.',
      ],
    }),
  },
  {
    slug: 'dia-dos-pais',
    layout: 'timeline',
    name: 'Dia dos Pais',
    category: 'dia-dos-pais',
    tributeTypeSlug: 'dia-dos-pais',
    description: 'Visual elegante com linha do tempo de momentos especiais e galeria da família.',
    theme: {
      primaryColor: '#0f766e',
      accentColor: '#5eead4',
      fontDisplay: "'Fraunces', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #f2f8f7 0%, #eef4f6 100%)',
      mode: 'light',
    },
    animation: { speed: 'normal', entrance: 'slide-up' },
    effects: [],
    capabilities: { maxPhotos: 20, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', eyebrow: 'Para você, pai' } },
      { id: 'msg', type: 'typewriter' },
      { id: 'timeline', type: 'timeline', config: { title: 'Momentos que guardo' } },
      { id: 'gallery', type: 'gallery', config: { layout: 'masonry', title: 'Nossa família' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com admiração,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Pai',
      senderName: 'Seus filhos',
      title: 'Ao meu herói',
      subtitle: 'Exemplo de força, trabalho e amor',
      message: 'Você me ensinou, pelo exemplo, o que significa ser íntegro e cuidar de quem se ama.',
      closingMessage: 'Obrigado por tudo, pai.',
      signature: 'Seus filhos',
      photos: samplePhotos(6, 'Família'),
    }),
  },
  {
    slug: 'casamento',
    layout: 'storytelling',
    name: 'Casamento',
    category: 'casamento',
    tributeTypeSlug: 'casamento',
    description: 'Convite digital com contagem regressiva, história do casal e galeria.',
    theme: {
      primaryColor: '#b08968',
      accentColor: '#ddb892',
      fontDisplay: "'Cormorant Garamond', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #faf6f0 0%, #f3ebe0 100%)',
      mode: 'light',
    },
    animation: { speed: 'slow', entrance: 'fade' },
    effects: ['petals'],
    capabilities: { maxPhotos: 24, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', parallax: true } },
      { id: 'story', type: 'typewriter', config: { eyebrow: 'Nossa história' } },
      { id: 'countdown', type: 'countdown', config: { mode: 'countdown', title: 'Contagem para o grande dia' } },
      { id: 'timeline', type: 'timeline', config: { title: 'Do primeiro encontro ao sim' } },
      { id: 'gallery', type: 'gallery', config: { layout: 'masonry', title: 'Nós dois' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Votos e desejos' } },
      { id: 'final', type: 'finalMessage', config: { text: 'E que a nossa história seja para sempre.' } },
      { id: 'signature', type: 'signature', config: { prefix: 'Com amor,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Marina & Rafael',
      senderName: 'Marina & Rafael',
      title: 'Vamos nos casar',
      subtitle: 'E queremos você ao nosso lado',
      message: 'Depois de tantos capítulos juntos, chegou a hora de escrever o mais importante.',
      closingMessage: 'E que a nossa história seja para sempre.',
      signature: 'Marina & Rafael',
      specialDate: inDays(60),
      photos: samplePhotos(6, 'Nós'),
      timeline: [
        { date: '2018', title: 'O primeiro encontro', description: 'Um acaso que mudou tudo.' },
        { date: '2022', title: 'Morar juntos', description: 'Nosso primeiro lar.' },
        { date: 'Hoje', title: 'O sim', description: 'O começo de para sempre.' },
      ],
    }),
  },
  {
    slug: 'cha-de-bebe',
    layout: 'album',
    name: 'Chá de Bebê',
    category: 'cha-de-bebe',
    tributeTypeSlug: 'cha-de-bebe',
    description: 'Tema suave com contagem regressiva, fotos da espera e recados da família.',
    theme: {
      primaryColor: '#60a5fa',
      accentColor: '#a5d8ff',
      fontDisplay: "'Poppins', sans-serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #f3f8ff 0%, #eef6f2 100%)',
      mode: 'light',
    },
    animation: { speed: 'normal', entrance: 'zoom' },
    effects: ['stars'],
    capabilities: { maxPhotos: 18, supportsVideo: false, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'card', eyebrow: 'Estamos esperando você' } },
      { id: 'countdown', type: 'countdown', config: { mode: 'countdown', title: 'Faltam poucos dias' } },
      { id: 'gallery', type: 'gallery', config: { layout: 'grid', title: 'A espera' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Recados para o bebê' } },
      { id: 'final', type: 'finalMessage', config: { text: 'Já te amamos tanto!' } },
      { id: 'signature', type: 'signature', config: { prefix: 'Com amor,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Nosso bebê',
      senderName: 'Papai e Mamãe',
      title: 'Bem-vindo, pequeno amor',
      subtitle: 'A nossa maior alegria está a caminho',
      message: 'Cada dia que passa nos aproxima do abraço mais esperado das nossas vidas.',
      closingMessage: 'Já te amamos tanto!',
      signature: 'Papai e Mamãe',
      specialDate: inDays(40),
      photos: samplePhotos(4, 'Espera'),
      messages: ['Que você venha com muita saúde! — Vovó', 'Contando os dias para te conhecer! — Titia'],
    }),
  },
  {
    slug: 'pedido-casamento',
    layout: 'proposal',
    name: 'Pedido de Casamento',
    category: 'pedido-casamento',
    tributeTypeSlug: 'pedido',
    description: 'Experiência cinematográfica com nossa história, fotos e um grande final.',
    theme: {
      primaryColor: '#be123c',
      accentColor: '#fb7185',
      fontDisplay: "'Playfair Display', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #14090c 0%, #24101a 100%)',
      mode: 'dark',
    },
    animation: { speed: 'slow', entrance: 'fade' },
    effects: ['hearts', 'fireworks'],
    capabilities: { maxPhotos: 16, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', parallax: true } },
      { id: 'story', type: 'typewriter', config: { eyebrow: 'A nossa história' } },
      { id: 'slider', type: 'photoSlider', config: { title: 'Momentos nossos' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Tudo o que sinto' } },
      { id: 'final', type: 'finalMessage', config: { text: 'Você aceita casar comigo?' } },
      { id: 'signature', type: 'signature', config: { prefix: 'Para sempre,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Meu amor',
      senderName: 'Eu',
      title: 'Desde que te conheci',
      subtitle: 'Cada dia foi um ensaio para esta pergunta',
      message: 'Eu poderia listar mil motivos, mas todos levam ao mesmo lugar: eu quero você, para sempre.',
      closingMessage: 'Você aceita casar comigo?',
      signature: 'Para sempre, eu',
      photos: samplePhotos(5, 'Nós'),
      messages: ['Você é a minha pessoa.', 'Quero envelhecer ao seu lado.'],
    }),
  },
  {
    slug: 'pedido-namoro',
    layout: 'proposal',
    name: 'Pedido de Namoro',
    category: 'pedido-namoro',
    tributeTypeSlug: 'pedido',
    description: 'Uma história em passos que termina no convite: "Quer namorar comigo?".',
    theme: {
      primaryColor: '#e11d48',
      accentColor: '#fb7185',
      fontDisplay: "'Dancing Script', cursive",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #1a0d13 0%, #2b1420 100%)',
      mode: 'dark',
    },
    animation: { speed: 'normal', entrance: 'slide-up' },
    effects: ['hearts'],
    capabilities: { maxPhotos: 12, supportsVideo: false, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', parallax: true } },
      { id: 'story', type: 'typewriter', config: { eyebrow: 'Desde que te conheci' } },
      { id: 'slider', type: 'photoSlider', config: { title: 'A gente' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'O que eu sinto' } },
      { id: 'final', type: 'finalMessage', config: { text: 'Quer namorar comigo?' } },
      { id: 'signature', type: 'signature', config: { prefix: 'Com o coração,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Você',
      senderName: 'Eu',
      title: 'Tenho uma pergunta pra você',
      subtitle: 'Prometo que vale a pena chegar até o final',
      message: 'Cada conversa, cada risada e cada saudade me trouxeram até aqui.',
      closingMessage: 'Quer namorar comigo?',
      signature: 'Com o coração, eu',
      photos: samplePhotos(5, 'A gente'),
      messages: ['Você deixa tudo mais leve.', 'Quero viver muitos "nossos" com você.'],
      question: 'Quer namorar comigo?',
      celebration: 'Ela disse SIM! 💞',
    }),
  },
  {
    slug: 'formatura',
    layout: 'timeline',
    name: 'Formatura',
    category: 'formatura',
    tributeTypeSlug: 'formatura',
    description: 'Celebração da trajetória com linha do tempo, galeria e mensagens da família.',
    theme: {
      primaryColor: '#1d4ed8',
      accentColor: '#fbbf24',
      fontDisplay: "'Poppins', sans-serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #f3f6ff 0%, #fdf7ec 100%)',
      mode: 'light',
    },
    animation: { speed: 'fast', entrance: 'zoom' },
    effects: ['confetti'],
    capabilities: { maxPhotos: 24, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', eyebrow: 'Conseguimos!' } },
      { id: 'timeline', type: 'timeline', config: { title: 'A trajetória' } },
      { id: 'slider', type: 'photoSlider', config: { title: 'Grandes momentos' } },
      { id: 'video', type: 'video' },
      { id: 'messages', type: 'messageSlider', config: { title: 'Mensagens de quem te ama' } },
      { id: 'final', type: 'finalMessage', config: { text: 'Este é só o começo!' } },
      { id: 'signature', type: 'signature', config: { prefix: 'Com orgulho,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Lucas',
      senderName: 'Sua família',
      title: 'Parabéns, formando!',
      subtitle: 'Anos de dedicação que valeram a pena',
      message: 'Cada madrugada de estudo e cada desafio te trouxeram até aqui. Você conseguiu!',
      closingMessage: 'Este é só o começo!',
      signature: 'Com orgulho, sua família',
      photos: samplePhotos(6, 'Jornada'),
      timeline: [
        { date: 'Ano 1', title: 'O início', description: 'Novos amigos e muitos sonhos.' },
        { date: 'Ano 3', title: 'Superação', description: 'Provas, projetos e conquistas.' },
        { date: 'Hoje', title: 'A formatura', description: 'O diploma nas mãos.' },
      ],
    }),
  },
  {
    slug: 'natal',
    layout: 'storytelling',
    name: 'Natal',
    category: 'natal',
    tributeTypeSlug: 'natal',
    description: 'Cartão natalino com neve animada, fotos da família e mensagem especial.',
    theme: {
      primaryColor: '#c1121f',
      accentColor: '#e5c07b',
      fontDisplay: "'Fraunces', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #0d2818 0%, #123524 100%)',
      mode: 'dark',
    },
    animation: { speed: 'slow', entrance: 'fade' },
    effects: ['snow'],
    capabilities: { maxPhotos: 18, supportsVideo: false, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', eyebrow: 'Feliz Natal' } },
      { id: 'msg', type: 'typewriter' },
      { id: 'gallery', type: 'gallery', config: { layout: 'masonry', title: 'Nosso Natal' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Votos de fim de ano' } },
      { id: 'final', type: 'finalMessage', config: { text: 'Que seu Natal seja repleto de luz.' } },
      { id: 'signature', type: 'signature', config: { prefix: 'Com carinho,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Família querida',
      senderName: 'Com carinho',
      title: 'Feliz Natal',
      subtitle: 'Que a magia desta noite aqueça o seu coração',
      message: 'Que o Natal traga paz, união e a alegria de estarmos juntos por mais um ano.',
      closingMessage: 'Que seu Natal seja repleto de luz.',
      signature: 'Com carinho, sua família',
      photos: samplePhotos(5, 'Natal'),
      messages: ['Que 2025 seja de muitas bênçãos!', 'Feliz Natal para toda a família!'],
    }),
  },
  {
    slug: 'ano-novo',
    layout: 'cinematic',
    name: 'Ano Novo',
    category: 'ano-novo',
    tributeTypeSlug: 'ano-novo',
    description: 'Contagem regressiva para a virada, fogos animados e retrospectiva em fotos.',
    theme: {
      primaryColor: '#eab308',
      accentColor: '#fde68a',
      fontDisplay: "'Poppins', sans-serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #0a0f1f 0%, #131a33 100%)',
      mode: 'dark',
    },
    animation: { speed: 'normal', entrance: 'zoom' },
    effects: ['fireworks', 'stars'],
    capabilities: { maxPhotos: 20, supportsVideo: false, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', eyebrow: 'Feliz Ano Novo' } },
      { id: 'countdown', type: 'countdown', config: { mode: 'countdown', title: 'Contagem para a virada' } },
      { id: 'slider', type: 'photoSlider', config: { title: 'Retrospectiva' } },
      { id: 'msg', type: 'typewriter', config: { eyebrow: 'Para o próximo ano' } },
      { id: 'final', type: 'finalMessage', config: { text: 'Que venha um ano de conquistas!' } },
      { id: 'signature', type: 'signature', config: { prefix: 'Com esperança,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Você',
      senderName: 'Com esperança',
      title: 'Um brinde ao novo ano',
      subtitle: 'Novos sonhos, novas conquistas',
      message: 'Que cada dia do próximo ano seja uma página em branco cheia de possibilidades.',
      closingMessage: 'Que venha um ano de conquistas!',
      signature: 'Com esperança',
      specialDate: inDays(30),
      photos: samplePhotos(6, 'Momento'),
    }),
  },
  {
    slug: 'dia-da-mulher',
    layout: 'album',
    name: 'Dia da Mulher',
    category: 'datas',
    tributeTypeSlug: 'dia-da-mulher',
    description: 'Layout elegante com flores animadas, galeria e mensagens de admiração.',
    theme: {
      primaryColor: '#9333ea',
      accentColor: '#e879f9',
      fontDisplay: "'Cormorant Garamond', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #faf5ff 0%, #fdf2fb 100%)',
      mode: 'light',
    },
    animation: { speed: 'normal', entrance: 'slide-up' },
    effects: ['petals'],
    capabilities: { maxPhotos: 18, supportsVideo: false, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'card', eyebrow: 'Para você, mulher' } },
      { id: 'msg', type: 'typewriter' },
      { id: 'gallery', type: 'gallery', config: { layout: 'masonry', title: 'Força e beleza' } },
      { id: 'messages', type: 'messageSlider', config: { title: 'Palavras de admiração' } },
      { id: 'final', type: 'finalMessage' },
      { id: 'signature', type: 'signature', config: { prefix: 'Com admiração,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Mulher incrível',
      senderName: 'Com admiração',
      title: 'À sua força e delicadeza',
      subtitle: 'Você transforma o mundo ao seu redor',
      message: 'A sua coragem inspira, a sua ternura acolhe. Ser mulher é ser potência e poesia.',
      closingMessage: 'Que você seja sempre livre para ser quem é.',
      signature: 'Com admiração',
      photos: samplePhotos(5, 'Você'),
      messages: ['Você é inspiração para todas nós.', 'Sua força move montanhas.'],
    }),
  },
  {
    slug: 'dia-dos-professores',
    layout: 'scroll',
    name: 'Dia dos Professores',
    category: 'agradecimento',
    tributeTypeSlug: 'dia-dos-professores',
    description: 'Agradecimento com mensagens dos alunos, galeria e vídeo.',
    theme: {
      primaryColor: '#0891b2',
      accentColor: '#f59e0b',
      fontDisplay: "'Fraunces', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #f1f9fb 0%, #fdf6ea 100%)',
      mode: 'light',
    },
    animation: { speed: 'normal', entrance: 'slide-up' },
    effects: [],
    capabilities: { maxPhotos: 18, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'card', eyebrow: 'Obrigado, professor(a)' } },
      { id: 'msg', type: 'typewriter' },
      { id: 'messages', type: 'messageSlider', config: { title: 'Recados dos alunos' } },
      { id: 'gallery', type: 'gallery', config: { layout: 'grid', title: 'Nossa turma' } },
      { id: 'video', type: 'video' },
      { id: 'final', type: 'finalMessage', config: { text: 'Gratidão por tudo que nos ensinou.' } },
      { id: 'signature', type: 'signature', config: { prefix: 'Com gratidão,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Professora Ana',
      senderName: 'Seus alunos',
      title: 'Obrigado por ensinar com o coração',
      subtitle: 'Um mestre que deixa marcas para a vida',
      message: 'A senhora ensinou muito além dos livros: ensinou a acreditar em nós mesmos.',
      closingMessage: 'Gratidão por tudo que nos ensinou.',
      signature: 'Com gratidão, seus alunos',
      photos: samplePhotos(4, 'Turma'),
      messages: ['A senhora mudou o meu jeito de ver o mundo. — Pedro', 'Obrigada por tanta paciência! — Júlia'],
    }),
  },
  {
    slug: 'historia-vida',
    layout: 'storytelling',
    name: 'História da Nossa Vida',
    category: 'outras',
    tributeTypeSlug: 'historia',
    description: 'Experiência em storytelling: cada seção é um capítulo com fotos, vídeo e textos.',
    theme: {
      primaryColor: '#a16207',
      accentColor: '#d4a373',
      fontDisplay: "'Fraunces', serif",
      fontBody: FONT_BODY,
      background: 'linear-gradient(180deg, #faf7f2 0%, #f4eee4 100%)',
      mode: 'light',
    },
    animation: { speed: 'slow', entrance: 'fade' },
    effects: [],
    capabilities: { maxPhotos: 30, supportsVideo: true, supportsMusic: true },
    sections: [
      { id: 'hero', type: 'hero', config: { variant: 'fullscreen', parallax: true } },
      { id: 'msg', type: 'typewriter', config: { eyebrow: 'Capítulo um' } },
      { id: 'timeline', type: 'timeline', config: { title: 'Os capítulos' } },
      { id: 'gallery', type: 'gallery', config: { layout: 'masonry', title: 'Cenas da nossa vida' } },
      { id: 'slider', type: 'photoSlider', config: { title: 'Momentos marcantes' } },
      { id: 'video', type: 'video' },
      { id: 'messages', type: 'messageSlider', config: { title: 'O que aprendemos' } },
      { id: 'final', type: 'finalMessage', config: { text: 'E a história continua...' } },
      { id: 'signature', type: 'signature', config: { prefix: 'Com amor,' } },
    ],
    sampleContent: makeSample({
      honoreeName: 'Nós',
      senderName: 'Com amor',
      title: 'A história da nossa vida',
      subtitle: 'Um livro escrito a cada dia, juntos',
      message: 'Toda vida é feita de capítulos. Estes são alguns dos nossos favoritos.',
      closingMessage: 'E a história continua...',
      signature: 'Com amor',
      photos: samplePhotos(6, 'Cena'),
    }),
  },
]
